#!/usr/bin/env python3
"""
Clean Weibo usage corpus to produce a version more suitable for XL‑LEXEME.

This script reads a JSON list of usage records (as generated by the
``weibo_crawler.py`` script) and applies several text‐cleaning
operations to the ``raw_text``/``normalized_text`` fields.  It also
recomputes the context spans (``left_context``/``right_context``) and
target indices (``target_start``/``target_end``) based on the cleaned
text.  Records that no longer contain the target word after cleaning
are dropped.  The ``timestamp`` field is removed as it is unused in
the current pipeline.

Usage:

    python data_cleaning.py --input raw_weibo_usage_corpus.json \
                            --output weibo_usage_corpus.json

The script can also be imported as a module and its ``clean_text``
function reused in other preprocessing pipelines.

Note: This cleaner is opinionated and tailored to the noise patterns
commonly seen in Weibo posts.  You may wish to adjust the regular
expressions if you encounter additional patterns.
"""

import argparse
import json
import re
from typing import Any, Dict, Iterable, List, Optional

# Regular expressions for various noise patterns.  We precompile
# patterns for efficiency and clarity.  Each pattern will be removed
# from the text.
URL_RE = re.compile(r"http[s]?://\S+")
# Hashtags of the form #xxx#; non‑greedy to avoid spanning across
# unrelated content.
HASHTAG_RE = re.compile(r"#.*?#")
# Weibo video links: sequences starting with optional 'L' plus some
# non‑space characters and ending with '的微博视频'.  We allow up to
# 50 non‑space characters to cover usernames and channel names.  This
# matches patterns like 'L 西班牙陈挺的微博视频' or '西班牙陈挺的微博视频'.
WEIBO_VIDEO_RE = re.compile(r"L?\s*[^\s\u3000]{0,50}?的微博视频")
# General labels like '微博视频', '网页链接', '转发微博', '展开全文', '收起全文'
GENERIC_TAG_RE = re.compile(
    r"(微博视频|网页链接|转发微博|展开全文|收起全文|抽奖|分享图片|分享视频|分享微博|分享歌曲)"
)
# At‑mentions of the form @用户名（不包含空格和中文标点）。
AT_MENTION_RE = re.compile(r"@[\w-]+")
# Weibo emojis enclosed in square brackets, e.g. [笑哭]
EMOJI_RE = re.compile(r"\[.*?\]")
# Zero‑width spaces and miscellaneous control characters.
CONTROL_CHARS_RE = re.compile(r"[\u200b\u200c\u200d]+")
# Multiple spaces/newlines.
MULTISPACE_RE = re.compile(r"\s+")


def clean_text(text: str) -> str:
    """Remove common Weibo noise patterns from a post.

    Parameters
    ----------
    text : str
        The original raw text of the post.

    Returns
    -------
    str
        The cleaned text with noise removed and extra whitespace
        collapsed.  Leading and trailing whitespace are stripped.
    """
    # Remove URLs first to avoid interfering with other patterns.
    text = URL_RE.sub("", text)
    # Remove video link patterns like 'L xxx的微博视频'
    text = WEIBO_VIDEO_RE.sub("", text)
    # Remove generic tags and short content markers.
    text = GENERIC_TAG_RE.sub("", text)
    # Remove hashtags (e.g. #话题#).  Use non‑greedy match to drop
    # each hashtag individually.  If unmatched trailing '#' remains,
    # later whitespace collapsing will clean it.
    text = HASHTAG_RE.sub("", text)
    # Remove at‑mentions
    text = AT_MENTION_RE.sub("", text)
    # Remove bracketed emojis
    text = EMOJI_RE.sub("", text)
    # Remove control characters like zero‑width spaces
    text = CONTROL_CHARS_RE.sub("", text)
    # Collapse multiple whitespace to a single space
    text = MULTISPACE_RE.sub(" ", text)
    return text.strip()


def update_record(record: Dict[str, Any]) -> Optional[Dict[str, Any]]:
    """Clean a single usage record and recompute contextual fields.

    Parameters
    ----------
    record : dict
        A dictionary representing a usage instance.  Required keys
        include ``target_word`` and at least one of ``raw_text`` or
        ``normalized_text``.

    Returns
    -------
    dict or None
        The updated record with cleaned text and recomputed spans, or
        None if the cleaned text no longer contains the target word.
    """
    target = record.get("target_word")
    if not target:
        # Malformed record; skip.
        return None
    original = record.get("raw_text") or record.get("normalized_text") or ""
    cleaned = clean_text(original)
    # Ensure the target word is still present; otherwise drop this record.
    idx = cleaned.find(target)
    if idx < 0:
        return None
    # Compute left and right context strings
    left = cleaned[:idx].strip()
    right = cleaned[idx + len(target) :].strip()
    # Update fields
    record["normalized_text"] = cleaned
    record["full_context"] = cleaned
    record["left_context"] = left
    record["right_context"] = right
    record["target_start"] = idx
    record["target_end"] = idx + len(target)
    # Remove unused timestamp field
    if "timestamp" in record:
        record.pop("timestamp", None)
    # The flags is_duplicate/is_short_context/is_noisy are reset based on new content.
    record["is_duplicate"] = False
    record["is_short_context"] = len(cleaned) < 8
    record["is_noisy"] = False
    return record


def process_corpus(records: Iterable[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Clean all usage records and return a filtered list.

    Parameters
    ----------
    records : iterable of dicts
        Sequence of usage records to clean.

    Returns
    -------
    list of dicts
        The cleaned records with only those where the target word is
        present after cleaning.
    """
    cleaned_records: List[Dict[str, Any]] = []
    for rec in records:
        new_rec = update_record(rec.copy())
        if new_rec:
            cleaned_records.append(new_rec)
    return cleaned_records


def main(input_path: str, output_path: str) -> None:
    """Load, clean and save the usage corpus.

    This function reads from ``input_path``, processes each record, and
    writes the cleaned list to ``output_path`` in JSON format with
    UTF‑8 encoding and two‑space indentation for readability.
    """
    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    cleaned = process_corpus(data)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(cleaned, f, ensure_ascii=False, indent=2)
    print(f"Input records: {len(data)}, kept after cleaning: {len(cleaned)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Clean Weibo usage corpus for XL‑LEXEME"
    )
    parser.add_argument(
        "--input",
        default="raw_weibo_usage_corpus.json",
        help="Path to the input JSON corpus",
    )
    parser.add_argument(
        "--output",
        default="weibo_usage_corpus.json",
        help="Path to write the cleaned JSON corpus",
    )
    args = parser.parse_args()
    main(args.input, args.output)